##
## Build
##

FROM golang:1.21.1-alpine AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

# COPY ./*.go ./
COPY . ./

RUN go build -o /tech-blog-api

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /tech-blog-api /tech-blog-api

EXPOSE 1323

USER nonroot:nonroot

ENTRYPOINT ["/tech-blog-api"]
