
-- +migrate Up
CREATE TABLE IF NOT EXISTS tags (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS tags;
